"""migration

Revision ID: 42a81873db5f
Revises: f8b1a80e609b
Create Date: 2024-05-24 11:27:14.583908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42a81873db5f'
down_revision = 'f8b1a80e609b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_delete', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('folders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_delete', sa.Boolean(), nullable=True))

    with op.batch_alter_table('shares', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shared_with_user_email', sa.String(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['shared_with_user_email'], ['email'])
        batch_op.drop_column('shared_with_user_id')

    with op.batch_alter_table('starred_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('folder_id', sa.Integer(), nullable=True))
        batch_op.alter_column('file_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(None, 'folders', ['folder_id'], ['id'])

    with op.batch_alter_table('trash_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('folder_id', sa.Integer(), nullable=True))
        batch_op.alter_column('file_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(None, 'folders', ['folder_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trash_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('file_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('folder_id')

    with op.batch_alter_table('starred_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('file_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('folder_id')

    with op.batch_alter_table('shares', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shared_with_user_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['shared_with_user_id'], ['id'])
        batch_op.drop_column('shared_with_user_email')

    with op.batch_alter_table('folders', schema=None) as batch_op:
        batch_op.drop_column('is_delete')

    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('is_delete')

    # ### end Alembic commands ###
