"""added is starred columns

Revision ID: 95521c6e29a9
Revises: 467b92a51617
Create Date: 2024-05-27 14:16:03.963745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95521c6e29a9'
down_revision = '467b92a51617'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_starred', sa.Boolean(), nullable=True))

    with op.batch_alter_table('folders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_starred', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('folders', schema=None) as batch_op:
        batch_op.drop_column('is_starred')

    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_column('is_starred')

    # ### end Alembic commands ###
