"""new miration

Revision ID: b1bdb1f0df9f
Revises: 1d5c02f0b5a1
Create Date: 2024-05-22 13:57:08.555916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1bdb1f0df9f'
down_revision = '1d5c02f0b5a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trash_items', schema=None) as batch_op:
        batch_op.drop_constraint('fk_trash_items_folder_id', type_='foreignkey')
        batch_op.drop_column('folder_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trash_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('folder_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key('fk_trash_items_folder_id', 'folders', ['folder_id'], ['id'])

    # ### end Alembic commands ###
